### PR TITLE
Unused items

### PR DESCRIPTION
**Pull request by CM30**
Since I've been working with them for a video, I added all the game's unused items to the editor, including the removed materials, ending armour, sage weapons, Ganondorf's weapons, misc weapons like Construct arms and unusual unused materials like house pieces and Yiga Clan members.

All data is taken from this parameter spreadsheet:

https://docs.google.com/spreadsheets/d/1YkGXGsYIr91d00Lri2cTXYtorRfoMkZNbS1I_4mZLGc/edit#gid=743259495

I accept you might decline this due to some of these being buggy when modded into a save file, but I can guarantee from my testing that they all work in some capacity when added to your inventory.

### CODE REVIEW

**Comment by marcrobledo** [comment]
Indeed, most of these were already in the very early versions of the editor. But I removed most of them because people was getting confused and I was getting a lot of complains.

I don't mind readding them at this point, but I'd like them to be added to the end of every dropdown, and maybe use a prefix starting with a  *, so they can be easily differentiated. Do you mind doing an edit?

**Comment by CM30** [comment]
> Indeed, most of these were already in the very early versions of the editor. But I removed most of them because people was getting confused and I was getting a lot of complains.
> 
> I don't mind readding them at this point, but I'd like them to be added to the end of every dropdown, and maybe use a prefix starting with a *, so they can be easily differentiated. Do you mind doing an edit?

I've now moved all unused items to the end of their respective categories (like the glitched Master Sword and Zelda's torch are in the existing version), and prefixed them with *.

Hopefully that should now differentiate them more clearly.

**Comment by marcrobledo** [comment]
Thank you!

Just before I merge the PR...
Have all these tested in-game? Are all safe to use? If there is any that can glitch or freeze the game, it might be better to remove them.

**Comment by CM30** [comment]
> Thank you!
> 
> Just before I merge the PR... Have all these tested in-game? Are all safe to use? If there is any that can glitch or freeze the game, it might be better to remove them.

Got all of them to work in game.

That said, the Blademaster running the Yiga Clan Hideout can only be summoned once when used as an item, at least til you warp/change map/reload. So there may need to be a note there. It's insane for escaping boss battles and mini games, but can be risky.

For the most part the items work as usual, though some of the weird NPC specific weapons (the GoronKnuckle and Mineru Construct related ones) can freeze if you fuse something to them.

No problems I can see with things like beam emitters, the rock ball, cushions, weird treasure chests, sage weapons, etc.

**Comment by marcrobledo** [comment]
Sorry for being so nitpicky 😅
But I know what happens when you add things to the editor that can freeze the game. I figure, a year after the release, there should be less people hacking the game so I guess I could merge the PR.


However, I have a last question... I've seen some odd things that caught my attention:
- **food effects like TwiceJump**: do they work in-game? I recall testing all of them and only keeping in the editor the ones that worked. I could have missed some of them, but I'm pretty sure I'd have left a double jump effect if it worked.
- **items like Obj_LinkHouse_, Npc_Assassin_Junior_, Obj_Photo_ or Obj_Warp**: are they really items? are they usable? 
I'd rather prefer to keep the list clean with only items that really work or do something in-game.

**Comment by CM30** [comment]
> Sorry for being so nitpicky 😅 But I know what happens when you add things to the editor that can freeze the game. I figure, a year after the release, there should be less people hacking the game so I guess I could merge the PR.
> 
> However, I have a last question... I've seen some odd things that caught my attention:
> 
>     * **food effects like TwiceJump**: do they work in-game? I recall testing all of them and only keeping in the editor the ones that worked. I could have missed some of them, but I'm pretty sure I'd have left a double jump effect if it worked.
> 
>     * **items like Obj_LinkHouse_, Npc_Assassin_Junior_, Obj_Photo_ or Obj_Warp**: are they really items? are they usable?
>       I'd rather prefer to keep the list clean with only items that really work or do something in-game.

Just going to break down the items by functionality:

- All house parts work as expected. You'll have to drop them while gliding to summon them, but you can literally build a house anywhere in the game, including the Depths, sky islands, dungeons, shrines, the prologue, etc. So no issues there.
- Dungeon Beam Emitter and Kohga's Rock Ball Projectile work as expected too. You can summon them anywhere, cook them, etc)
- Cushions and fake Octorok treasure chests work as expected in all circumstances
- Sage weapons work as expected, whether they be bows or melee weapons. Same with unused torches
- NPC/Link's farm food, meat from enemy camps and other display items work as expected in game
- The restored Link's arm armour and the unused BoTW hairstyle armour work as expected
- Unused Zonai armour is weird. Works like the normal one in game, but changes half of Link's model in the inventory. I'd say it's probably useable enough
- That red laser beam from shrines crashed when placed on one file, but worked fine on another. Based on how the old file seems to be somewhat corrupted from mods, it seems like it's fine on a normal file
- Unused food effects display text in the menu, but have no effect in game
- The Yiga Assassin items work, but are somewhat weird in terms of stability. The normal Assassin_Junior and Assassin_Senior ones are 100% stable, though have to be summoned while gliding. The shopkeepers and mini game host can only have one copy summoned at a time and are a lot less stable, though potentially interesting enough to be relevant.
- Starlight Memories display items are useless, so could probably be left out
- Dummy armour is obviously useless, so could probably be left out
- Unused Zonaite is incredibly unstable, so might be best to leave out to avoid confusion
- Selmie's shields are perfectly usable in all ways
- I need to test the Obj_Photo and Obj_Warp items on a new file, since they might enable that functionality early. They're pretty useless on an existing one though.

So I think to summarise:

- House rooms, dungeon items, sage equipment, unused torches/weapons/shields, display items, cushions, fake treasure chests, and ending armour would probably be good to include without any caveats
- Yiga stuff I'm mixed on, since they're less stable, but so hilariously game breaking that I'm sure a bunch of people probably want to mess around with them now the video is out
- Unused Zonaite may be too broken to include
- Dummy items, Starlight Memories display items, unused food effects, etc are too non functional to include

**Comment by marcrobledo** [comment]
> So I think to summarise:
> 
>     * House rooms, dungeon items, sage equipment, unused torches/weapons/shields, display items, cushions, fake treasure chests, and ending armour would probably be good to include without any caveats
> 
>     * Yiga stuff I'm mixed on, since they're less stable, but so hilariously game breaking that I'm sure a bunch of people probably want to mess around with them now the video is out
> 
>     * Unused Zonaite may be too broken to include
> 
>     * Dummy items, Starlight Memories display items, unused food effects, etc are too non functional to include

Looks fine to me. Let's keep everything that is usable, and remove anything that does nothing in-game or it's unstable.

As of...
- Yiga stuff: what if you put them to the end of the list and add two wildcards as their prefix?
- Obj_Photo and Obj_Warp: I'll wait until you confirm they can be used. Although, IIRC, they did nothing but take up an item slot.

Thank you, and sorry it's taking too long. I'm just being cautious.

**Comment by CM30** [comment]
> > So I think to summarise:
> > ```
> > * House rooms, dungeon items, sage equipment, unused torches/weapons/shields, display items, cushions, fake treasure chests, and ending armour would probably be good to include without any caveats
> > 
> > * Yiga stuff I'm mixed on, since they're less stable, but so hilariously game breaking that I'm sure a bunch of people probably want to mess around with them now the video is out
> > 
> > * Unused Zonaite may be too broken to include
> > 
> > * Dummy items, Starlight Memories display items, unused food effects, etc are too non functional to include
> > ```
> 
> Looks fine to me. Let's keep everything that is usable, and remove anything that does nothing in-game or it's unstable.
> 
> As of...
> 
>     * Yiga stuff: what if you put them to the end of the list and add two wildcards as their prefix?
> 
>     * Obj_Photo and Obj_Warp: I'll wait until you confirm they can be used. Although, IIRC, they did nothing but take up an item slot.
> 
> 
> Thank you, and sorry it's taking too long. I'm just being cautious.

No worries. The Yiga stuff is now at the end of the list with two wildcards, and the unusable items are now removed from the editor. Should be stable now I think.

**Comment by marcrobledo** [comment]
Thank you for your contribution!
Merging at last!

**Pull request merged**
