### PR TITLE
Adding Sage's Will coordinates

### PR DESCRIPTION
**Pull request by Shideravan**

### CODE REVIEW

**Review by marcrobledo — CHANGES_REQUESTED** [review]
Though I appreciate the contribution, I'm afraid this isn't as easy as just copying and pasting the coordinates.

- we need the raw coordinates, not the in-game coordinates (though this is not a big problem as it's easy to transform them)
- we are missing the obtained flags, which is the most important data in order to make the editor be able to know which items are obtained or not
- once we get the obtained flags, then we need to make them match to the same order as the items
- additional tip: if a number has leading zeroes, it becomes an octal in Javascript ;-) we can only use integers or floats in this case

I could accept the PR if you turn the coordinates into raw coordinates and remove the leading zeroes. Still, it won't be usable until someone finds the flags for every chest.

**Comment by Shideravan** [comment]
How do you convert the in-game coordinates to raw coordinates?

**Comment by marcrobledo** [comment]
> How do you convert the in-game coordinates to raw coordinates?

You need to:
- swap the second and third coordinates
- change sign to the second coordinate (which was the third!)
- add 105 to the third coordinate (which was the second!)

**Comment by marcrobledo** [comment]
Thank you for your contribution.

Unfortunately, as I said, this is not going to change anything, as we still need the respetictive flag hashes.

**Pull request merged**
